import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar/Sidebar'
import { ThemeProvider as NextThemeProvider } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      {/* <NextThemeProvider attribute="class" defaultTheme="dark"> */}
        <body className={inter.className}>{children}
          {/* <main>{children}</main> */}
          {/* <Sidebar /> */}
        </body>
      {/* </NextThemeProvider> */}
    </html>
  )
}
